export const sections = [
  { id: 'hero', name: 'Hero', icon: '🏠', description: 'Main banner with headline and CTA' },
  { id: 'features', name: 'Features', icon: '⭐', description: 'Key features and benefits' },
  { id: 'testimonials', name: 'Testimonials', icon: '💬', description: 'Client reviews and ratings' },
  { id: 'pricing', name: 'Pricing', icon: '💰', description: 'Pricing plans and packages' },
  { id: 'about', name: 'About', icon: '📖', description: 'Company or product story' },
  { id: 'cta', name: 'Call to Action', icon: '📢', description: 'Action buttons and prompts' },
  { id: 'menu', name: 'Navigation', icon: '🧭', description: 'Menu and navigation links' },
  { id: 'footer', name: 'Footer', icon: '🔗', description: 'Footer with links and info' },
  { id: 'gallery', name: 'Gallery', icon: '🖼️', description: 'Image or video gallery' },
  { id: 'contact', name: 'Contact', icon: '📧', description: 'Contact form and info' },
  { id: 'blog', name: 'Blog', icon: '📝', description: 'Latest articles and posts' },
  { id: 'newsletter', name: 'Newsletter', icon: '📬', description: 'Email subscription' },
  { id: 'stats', name: 'Statistics', icon: '📊', description: 'Metrics and statistics' },
  { id: 'team', name: 'Team', icon: '👥', description: 'Team members and profiles' },
  { id: 'faq', name: 'FAQ', icon: '❓', description: 'Frequently asked questions' },
  { id: 'timeline', name: 'Timeline', icon: '⏰', description: 'History and timeline' },
  { id: 'clients', name: 'Clients', icon: '🤝', description: 'Client logos and partners' },
  { id: 'videos', name: 'Videos', icon: '🎥', description: 'Video content and media' },
  { id: 'promo', name: 'Promo', icon: '🎁', description: 'Special promotions' },
  { id: 'announcement', name: 'Announcement', icon: '📣', description: 'Important announcements' },
  { id: 'properties', name: 'Properties', icon: '🏢', description: 'Property listings (Real Estate)' },
  { id: 'products', name: 'Products', icon: '🛍️', description: 'Product listings (E-commerce)' },
  { id: 'services', name: 'Services', icon: '🛠️', description: 'Service offerings' },
  { id: 'doctors', name: 'Doctors', icon: '👨‍⚕️', description: 'Medical professionals' },
  { id: 'courses', name: 'Courses', icon: '📚', description: 'Course listings' },
  { id: 'destinations', name: 'Destinations', icon: '🌍', description: 'Travel destinations' },
  { id: 'collections', name: 'Collections', icon: '👗', description: 'Fashion collections' },
  { id: 'menu-items', name: 'Menu Items', icon: '🍽️', description: 'Food and beverage menu' },
  { id: 'workouts', name: 'Workouts', icon: '🏋️', description: 'Fitness routines' },
  { id: 'models', name: 'Models', icon: '🚗', description: 'Automotive models' },
  { id: 'events', name: 'Events', icon: '🎪', description: 'Upcoming events' },
  { id: 'mission', name: 'Mission', icon: '🎯', description: 'Mission statement' },
  { id: 'case-studies', name: 'Case Studies', icon: '📋', description: 'Client success stories' },
  { id: 'integrations', name: 'Integrations', icon: '🔗', description: 'Third-party integrations' },
  { id: 'security', name: 'Security', icon: '🔒', description: 'Security features' },
  { id: 'appointments', name: 'Appointments', icon: '📅', description: 'Book appointments' },
  { id: 'donations', name: 'Donations', icon: '❤️', description: 'Donation options' },
  { id: 'volunteer', name: 'Volunteer', icon: '🤝', description: 'Volunteer opportunities' },
  { id: 'partners', name: 'Partners', icon: '🏢', description: 'Partner organizations' },
  { id: 'awards', name: 'Awards', icon: '🏆', description: 'Awards and recognition' },
  { id: 'press', name: 'Press', icon: '📰', description: 'Press coverage' },
  { id: 'careers', name: 'Careers', icon: '💼', description: 'Job openings' },
  { id: 'investors', name: 'Investors', icon: '📈', description: 'Investor relations' },
  { id: 'community', name: 'Community', icon: '🌐', description: 'Community engagement' },
  { id: 'sustainability', name: 'Sustainability', icon: '♻️', description: 'Sustainability efforts' },
  { id: 'innovation', name: 'Innovation', icon: '💡', description: 'Innovation stories' },
  { id: 'culture', name: 'Culture', icon: '🎨', description: 'Company culture' },
  { id: 'values', name: 'Values', icon: '⭐', description: 'Core values' },
  { id: 'history', name: 'History', icon: '📜', description: 'Company history' },
  { id: 'vision', name: 'Vision', icon: '🔭', description: 'Future vision' }
]
